version: '3.1'

volumes:
  pg_coffeeshop:


services:
  coffeeshop_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_coffeeshop:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - coffeeshop_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://coffeeshop_db:5432/coffeeshop_db'
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
