spring:
  application:
    name: coffieshop
  datasource:
    url: jdbc:postgresql://localhost:5432/coffieshop
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    password: xhdhdks
#    my own mail
    username: vrmarkov05@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  weather:
    api-key: ${SPRING_WEATHER_API_KEY}
